---
  # sample cloudlab configuration file
  region: us-east-2
  servers:
    - instance_type: m5.2xlarge
      private_ip_addresses: [101,102]
      roles:
        - ClusterMember

    - instance_type: m5.2xlarge
      private_ip_addresses: [103,104]
      roles:
        - Master

  open_ports:
    ClusterMember: [8888, 5701]
    Master: [8080]

