---
#
# Region independent names of some popular amis are below (as of Nov 2024)
#
# Amazon Linux 2023 (default ssh user: ec2-user)
# al2023-ami-2023.6.20241111.0-kernel-6.1-x86_64
# al2023-ami-2023.6.20241111.0-kernel-6.1-arm64
#
# Amazon Linux 2 (default ssh user: ec2-user)
# amzn2-ami-kernel-5.10-hvm-2.0.20241113.1-x86_64-gp2
# amzn2-ami-kernel-5.10-hvm-2.0.20241113.1-arm64-gp2
#
# Ubuntu Server 24.04 LTS (default ssh user: ubuntu)
# ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20240927
# ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-arm64-server-20240927
#
# Ubuntu Server 22.04 LTS (default ssh user: ubuntu)
# ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240927
# ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20240927
#
region: us-east-2
cidr: 10.0.0.0/16  # must be a /16 subnet, must be a non-routable (private) IP
roles:
  ClusterMember:
    instance_type: m5.xlarge
    ami_name: ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20240927
    ssh_user: ubuntu
    open_ports: [5701, 5702]
  LoadGenerator:
    instance_type: m5.xlarge
    ami_name: al2023-ami-2023.6.20241111.0-kernel-6.1-x86_64  # will look up the correct one for this region
    ssh_user: ec2-user
    open_ports: [8080]
subnets:
  - az: a                  # will be appended to region, e.g. us-east-2a
    cidr: 10.0.1.0/24      # must be a /24
    servers:
      # if private_ip_address_suffix is a list, then multiple servers will be created
      - private_ip_suffixes: [101, 102]   # only need to give the last octet 10.0.1.101
        role: ClusterMember
  - az: b
    cidr: 10.0.2.0/24
    servers:
      - private_ip_suffixes: [101, 102]   # becomes 10.0.2.101, 102
        role: ClusterMember
      - private_ip_suffixes: [201]
        role: LoadGenerator
